In [3]:
import numpy as np 
import pandas as pd

In [4]:
"""  Normalization of Data Using Numpy. Thus with the formula, (a - np.mean(a))/np.std(a) """

a = np.array([1, 2, 3, 4, 5, 6, 7])
z = (a - np.mean(a))/np.std(a)
z

array([-1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5])

In [5]:
np.std(z)

1.0

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
a
a.shape

(7,)

In [8]:
scaler = StandardScaler()          

In [9]:
a = a.reshape(-1, 1)
a.shape

(7, 1)

In [10]:
scaler.fit(a)

StandardScaler()

In [11]:
scaler.mean_

array([4.])

In [12]:
a

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [13]:
"""  To normalize the data """
scaler.transform(a)

array([[-1.5],
       [-1. ],
       [-0.5],
       [ 0. ],
       [ 0.5],
       [ 1. ],
       [ 1.5]])

In [14]:
scaler.fit_transform(a)

array([[-1.5],
       [-1. ],
       [-0.5],
       [ 0. ],
       [ 0.5],
       [ 1. ],
       [ 1.5]])

In [15]:
"""  STEPS IN MACHINE LEARNING
          1.  Import and Read the Data
          2.  Clean the Data
          3.  Split the Data into X and y (Features and Targets)
          4.  Further Split the Data into Training and Testing Set
          5.  Use a Model
          6.  Fit the Train Data set
          7.  Predict the Outcome of the Trained data
          8.  Check the Accuracy of the Data"""

"""  Key Words and Definition in Machine Learning
      Study of algot´rithm given a task (T), they improve their performance (P) based on experience (E) """

'  Key Words and Definition in Machine Learning\n      Study of algot´rithm given a task (T), they improve their performance (P) based on experience (E) '

In [16]:
"""  STEP 1 - Import the Data """

data_diabetes = pd.read_csv('diabetes.csv')
df_diabetes = pd.DataFrame(data_diabetes)
df_diabetes

FileNotFoundError: [Errno 2] No such file or directory: 'diabetes.csv'

In [ ]:
"""  STEP 2 - Cleaning the Data (Not YET)"""


'  STEP 2 - Cleaning the Data (Not YET)'

In [ ]:
"""  STEP 3 - Split the Data into X (Features) and y (Targets)  """

X = df_diabetes.drop('Outcome', axis=1)
y = df_diabetes['Outcome']
print(len(y))
print(len(X))

768
768


In [ ]:
"""  STEP 4 - Further Split the Data into Training and Testing Set  """

from sklearn.model_selection import train_test_split

X_train, X_test, y_train,  y_test = train_test_split(X, y, test_size=0.33, random_state=42)

print(len(X_train))
print(len(y_train))

514
514


In [ ]:
"""  STEP 4 - Splitting into folds  """

from sklearn.model_selection import KFold

kf = KFold(n_splits=2, shuffle=True)
kf.split(X)

<generator object _BaseKFold.split at 0x000002929789F200>

In [ ]:
"""  STEP 5 - Defining and Using a Model  """
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()

In [ ]:
"""  STEP 6 - Fiiting the Train set Data  """
model.fit(X_train, y_train)


DecisionTreeClassifier()

In [ ]:
"""  STEP 7 - Predicting the Model Outcome  """

predictions = model.predict(X_test)
predictions

array([1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1], dtype=int64)

In [ ]:
"""  STEP 7 - Checking the Accuracy  """

from sklearn.metrics import accuracy_score

score = accuracy_score(y_test, predictions)
score

0.7086614173228346

In [ ]:
y.describe()
y.value_counts()

0    500
1    268
Name: Outcome, dtype: int64

# SCALING THE DATA

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [ ]:
X_train.loc[:, :] = scaler.fit_transform(X_train)
X_train

In [ ]:
X_test.loc[:, :] = scaler.transform(X_test)
X_test

In [ ]:
model_standard = DecisionTreeClassifier()
model_standard.fit(X_train, y_train)

In [ ]:
predict = model_standard.predict(X_test)
predict

In [ ]:
score_standard = accuracy_score(y_test, predict)
score_standard

# ONE HOT ENCODING

In [ ]:
df = pd.DataFrame({'Animals' : ['dog', 'cat', 'dog', 'cat', 'car', 'beaver'], 'size' : [3, 2, 3, 2, 1, 6]})
df

Animals  size
0     dog     3
1     cat     2
2     dog     3
3     cat     2
4     car     1
5  beaver     6

In [ ]:
df.Animals.value_counts()

dog       2
cat       2
car       1
beaver    1
Name: Animals, dtype: int64

In [ ]:
pd.get_dummies(df.Animals, prefix='data')

data_beaver  data_car  data_cat  data_dog
0            0         0         0         1
1            0         0         1         0
2            0         0         0         1
3            0         0         1         0
4            0         1         0         0
5            1         0         0         0

In [ ]:
df1 = pd.concat([df.drop('Animals', axis=1), y], axis = 1)
df1 

size  Outcome
0     3.0        1
1     2.0        0
2     3.0        1
3     2.0        0
4     1.0        1
..    ...      ...
763   NaN        0
764   NaN        0
765   NaN        0
766   NaN        1
767   NaN        0

[768 rows x 2 columns]